### ISSUE TITLE
Migrate `docs` project

### ISSUE THREAD

**Issue by valencik** [typelevel/weaver-test#14]
Spun out of https://github.com/typelevel/weaver-test/pull/8

**Comment by CJSmith-0141** [comment]
I can take a crack at this? Should just be a matter of following the instructions here. https://typelevel.org/sbt-typelevel/site.html

**Comment by Baccata** [comment]
@CJSmith-0141 please do !

**Comment by CJSmith-0141** [comment]
Ok, opened up a PR here #17

**Comment by Baccata** [comment]
Closed in https://github.com/typelevel/weaver-test/pull/17
